const names = [
  {
    "id": 65021716,
    "node_id": "MDEwOlJlcG9zaXRvcnk2NTAyMTcxNg==",
    "name": "AngularJS",
  "favFoods":['tuna','fisk','frut'],
    "full_name": "HackYourFuture/AngularJS",
    "private": false,

    "owner": {
      "login": "HackYourFuture",
      "id": 20858568,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjIwODU4NTY4",
      "avatar_url": "https://avatars2.githubusercontent.com/u/20858568?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/HackYourFuture",
      "html_url": "https://github.com/HackYourFuture",
      "followers_url": "https://api.github.com/users/HackYourFuture/followers",
      "following_url": "https://api.github.com/users/HackYourFuture/following{/other_user}",
      "gists_url": "https://api.github.com/users/HackYourFuture/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/HackYourFuture/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/HackYourFuture/subscriptions",
      "organizations_url": "https://api.github.com/users/HackYourFuture/orgs",
      "repos_url": "https://api.github.com/users/HackYourFuture/repos",
      "events_url": "https://api.github.com/users/HackYourFuture/events{/privacy}",
      "received_events_url": "https://api.github.com/users/HackYourFuture/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "html_url": "https://github.com/HackYourFuture/AngularJS",
    "description": "Class material from angularJS module",
    "fork": false,
    "url": "https://api.github.com/repos/HackYourFuture/AngularJS",
    "forks_url": "https://api.github.com/repos/HackYourFuture/AngularJS/forks",
    "keys_url": "https://api.github.com/repos/HackYourFuture/AngularJS/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/HackYourFuture/AngularJS/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/HackYourFuture/AngularJS/teams",
    "hooks_url": "https://api.github.com/repos/HackYourFuture/AngularJS/hooks",
    "issue_events_url": "https://api.github.com/repos/HackYourFuture/AngularJS/issues/events{/number}",
    "events_url": "https://api.github.com/repos/HackYourFuture/AngularJS/events",
    "assignees_url": "https://api.github.com/repos/HackYourFuture/AngularJS/assignees{/user}",
    "branches_url": "https://api.github.com/repos/HackYourFuture/AngularJS/branches{/branch}",
    "tags_url": "https://api.github.com/repos/HackYourFuture/AngularJS/tags",
    "blobs_url": "https://api.github.com/repos/HackYourFuture/AngularJS/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/HackYourFuture/AngularJS/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/HackYourFuture/AngularJS/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/HackYourFuture/AngularJS/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/HackYourFuture/AngularJS/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/HackYourFuture/AngularJS/languages",
    "stargazers_url": "https://api.github.com/repos/HackYourFuture/AngularJS/stargazers",
    "contributors_url": "https://api.github.com/repos/HackYourFuture/AngularJS/contributors",
    "subscribers_url": "https://api.github.com/repos/HackYourFuture/AngularJS/subscribers",
    "subscription_url": "https://api.github.com/repos/HackYourFuture/AngularJS/subscription",
    "commits_url": "https://api.github.com/repos/HackYourFuture/AngularJS/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/HackYourFuture/AngularJS/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/HackYourFuture/AngularJS/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/HackYourFuture/AngularJS/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/HackYourFuture/AngularJS/contents/{+path}",
    "compare_url": "https://api.github.com/repos/HackYourFuture/AngularJS/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/HackYourFuture/AngularJS/merges",
    "archive_url": "https://api.github.com/repos/HackYourFuture/AngularJS/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/HackYourFuture/AngularJS/downloads",
    "issues_url": "https://api.github.com/repos/HackYourFuture/AngularJS/issues{/number}",
    "pulls_url": "https://api.github.com/repos/HackYourFuture/AngularJS/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/HackYourFuture/AngularJS/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/HackYourFuture/AngularJS/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/HackYourFuture/AngularJS/labels{/name}",
    "releases_url": "https://api.github.com/repos/HackYourFuture/AngularJS/releases{/id}",
    "deployments_url": "https://api.github.com/repos/HackYourFuture/AngularJS/deployments",
    "created_at": "2016-08-05T13:44:32Z",
    "updated_at": "2018-04-06T17:18:06Z",
    "pushed_at": "2017-02-02T10:10:02Z",
    "git_url": "git://github.com/HackYourFuture/AngularJS.git",
    "ssh_url": "git@github.com:HackYourFuture/AngularJS.git",
    "clone_url": "https://github.com/HackYourFuture/AngularJS.git",
    "svn_url": "https://github.com/HackYourFuture/AngularJS",
    "homepage": "",
    "size": 3480,
    "stargazers_count": 2,
    "watchers_count": 2,
    "language": "HTML",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 2,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "forks": 2,
    "open_issues": 0,
    "watchers": 2,
    "default_branch": "master",
    "permissions": {
      "admin": false,
      "push": false,
      "pull": true
    }
  },
  {
    "id": 66195249,
    "node_id": "MDEwOlJlcG9zaXRvcnk2NjE5NTI0OQ==",
    "name": "tdd-game",
    "favFoods":['tomat','orange'],
    "full_name": "HackYourFuture/tdd-game",
    "private": false,
    "owner": {
      "login": "HackYourFuture",
      "id": 20858568,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjIwODU4NTY4",
      "avatar_url": "https://avatars2.githubusercontent.com/u/20858568?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/HackYourFuture",
      "html_url": "https://github.com/HackYourFuture",
      "followers_url": "https://api.github.com/users/HackYourFuture/followers",
      "following_url": "https://api.github.com/users/HackYourFuture/following{/other_user}",
      "gists_url": "https://api.github.com/users/HackYourFuture/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/HackYourFuture/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/HackYourFuture/subscriptions",
      "organizations_url": "https://api.github.com/users/HackYourFuture/orgs",
      "repos_url": "https://api.github.com/users/HackYourFuture/repos",
      "events_url": "https://api.github.com/users/HackYourFuture/events{/privacy}",
      "received_events_url": "https://api.github.com/users/HackYourFuture/received_events",
      "type": "Organization",
      "site_admin": false
    },
    "html_url": "https://github.com/HackYourFuture/tdd-game",
    "description": null,
    "fork": false,
    "url": "https://api.github.com/repos/HackYourFuture/tdd-game",
    "forks_url": "https://api.github.com/repos/HackYourFuture/tdd-game/forks",
    "keys_url": "https://api.github.com/repos/HackYourFuture/tdd-game/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/HackYourFuture/tdd-game/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/HackYourFuture/tdd-game/teams",
    "hooks_url": "https://api.github.com/repos/HackYourFuture/tdd-game/hooks",
    "issue_events_url": "https://api.github.com/repos/HackYourFuture/tdd-game/issues/events{/number}",
    "events_url": "https://api.github.com/repos/HackYourFuture/tdd-game/events",
    "assignees_url": "https://api.github.com/repos/HackYourFuture/tdd-game/assignees{/user}",
    "branches_url": "https://api.github.com/repos/HackYourFuture/tdd-game/branches{/branch}",
    "tags_url": "https://api.github.com/repos/HackYourFuture/tdd-game/tags",
    "blobs_url": "https://api.github.com/repos/HackYourFuture/tdd-game/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/HackYourFuture/tdd-game/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/HackYourFuture/tdd-game/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/HackYourFuture/tdd-game/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/HackYourFuture/tdd-game/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/HackYourFuture/tdd-game/languages",
    "stargazers_url": "https://api.github.com/repos/HackYourFuture/tdd-game/stargazers",
    "contributors_url": "https://api.github.com/repos/HackYourFuture/tdd-game/contributors",
    "subscribers_url": "https://api.github.com/repos/HackYourFuture/tdd-game/subscribers",
    "subscription_url": "https://api.github.com/repos/HackYourFuture/tdd-game/subscription",
    "commits_url": "https://api.github.com/repos/HackYourFuture/tdd-game/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/HackYourFuture/tdd-game/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/HackYourFuture/tdd-game/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/HackYourFuture/tdd-game/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/HackYourFuture/tdd-game/contents/{+path}",
    "compare_url": "https://api.github.com/repos/HackYourFuture/tdd-game/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/HackYourFuture/tdd-game/merges",
    "archive_url": "https://api.github.com/repos/HackYourFuture/tdd-game/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/HackYourFuture/tdd-game/downloads",
    "issues_url": "https://api.github.com/repos/HackYourFuture/tdd-game/issues{/number}",
    "pulls_url": "https://api.github.com/repos/HackYourFuture/tdd-game/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/HackYourFuture/tdd-game/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/HackYourFuture/tdd-game/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/HackYourFuture/tdd-game/labels{/name}",
    "releases_url": "https://api.github.com/repos/HackYourFuture/tdd-game/releases{/id}",
    "deployments_url": "https://api.github.com/repos/HackYourFuture/tdd-game/deployments",
    "created_at": "2016-08-21T11:24:56Z",
    "updated_at": "2018-03-12T12:44:43Z",
    "pushed_at": "2016-08-21T13:58:49Z",
    "git_url": "git://github.com/HackYourFuture/tdd-game.git",
    "ssh_url": "git@github.com:HackYourFuture/tdd-game.git",
    "clone_url": "https://github.com/HackYourFuture/tdd-game.git",
    "svn_url": "https://github.com/HackYourFuture/tdd-game",
    "homepage": null,
    "size": 5,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 4,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "forks": 4,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master",
    "permissions": {
      "admin": false,
      "push": false,
      "pull": true
    }
  }
]


 function namesList (names){
  return `
  <div class ='name' id =${'div'+names.id} >
  <h1 class="title">    ${ names.name } </h1>
    <ul class="menu"> ${  true ?  names.favFoods.map( foods).join(' ') : false }</ul> 
  </div>
  `
} 

function foods(food){
  return `
   <li class='food'> ${food} </li>
  ` }

const divNames = window.document.createElement('div')
divNames.setAttribute('id','div1')
document.getElementById('main').appendChild(divNames)

document.getElementById('div1').innerHTML =
  `${names.map(namesList).join('')}`
  